import { asyncActionType } from '../utils/reduxActions';

export const FILTER_ACTIONS = {
    GET_CASES_LIST: asyncActionType('[CASE_MANAGEMENT]GET_CASES_LIST'),
    GET_CASES_LIST_BEGIN: '[CASE_MANAGEMENT]GET_CASE_LIST_BEGIN',

    GET_FILE_LIST: asyncActionType('[CASE_MANAGEMENT]GET_FILE_LIST'),
    GET_FILE_LIST_BEGIN: '[CASE_MANAGEMENT]GET_FILE_LIST_BEGIN',

    GET_CASE_ENTRIES_LIST: asyncActionType('[CASE_MANAGEMENT]GET_CASE_ENTRIES_LIST'),
    GET_CASE_ENTRIES_LIST_BEGIN: '[CASE_MANAGEMENT]GET_CASE_ENTRIES_LIST_BEGIN',

    SET_SELECTED_CASE_ID: '[CASE_MANAGEMENT]SET_SELECTED_CASE_ID',

    GET_CASE_ENTRIES_BY_ID: '[CASE_MANAGEMENT]GET_CASE_ENTRIES_BY_ID',

    EDIT_CASE_JOURNAL_ENTRY: asyncActionType('[CASE_MANAGEMENT]EDIT_CASE_JOURNAL_ENTRY'),
    EDIT_CASE_JOURNAL_ENTRY_BEGIN: '[CASE_MANAGEMENT]EDIT_CASE_JOURNAL_ENTRY_BEGIN',

    ADD_CASE_JOURNAL_ENTRY: asyncActionType('[CASE_MANAGEMENT]ADD_CASE_JOURNAL_ENTRY'),
    ADD_CASE_JOURNAL_ENTRY_BEGIN: '[CASE_MANAGEMENT]ADD_CASE_JOURNAL_ENTRY_BEGIN',

    DELETE_CASE_JOURNAL_ENTRY: asyncActionType('[CASE_MANAGEMENT]DELETE_CASE_JOURNAL_ENTRY'),
    DELETE_CASE_JOURNAL_ENTRY_BEGIN: '[CASE_MANAGEMENT]DELETE_CASE_JOURNAL_ENTRY_BEGIN',

    GET_CASE_DETAILS: asyncActionType('[CASE_MANAGEMENT]GET_CASE_DETAILS'),
    GET_CASE_DETAILS_BEGIN: '[CASE_MANAGEMENT]GET_CASE_DETAILS_BEGIN',

    DELETE_CASE_FILE: asyncActionType('[CASE_MANAGEMENT]DELETE_CASE_FILE'),
    DELETE_CASE_FILE_BEGIN: '[CASE_MANAGEMENT]DELETE_CASE_FILE_BEGIN',

    UPDATE_CASE_STATUS: asyncActionType('[CASE_MANAGEMENT]UPDATE_CASE_STATUS'),
    UPDATE_CASE_STATUS_BEGIN: '[CASE_MANAGEMENT]UPDATE_CASE_STATUS_BEGIN',

    DOWNLOAD_CASE_FILE: asyncActionType('[CASE_MANAGEMENT]DOWNLOAD_CASE_FILE'),
    DOWNLOAD_CASE_FILE_BEGIN: '[CASE_MANAGEMENT]DOWNLOAD_CASE_FILE_BEGIN',

    EDIT_CASE_DATA_ENTRY: asyncActionType('[CASE_MANAGEMENT]EDIT_CASE_DATA_ENTRY'),
    EDIT_CASE_DATA_ENTRY_BEGIN: '[CASE_MANAGEMENT]EDIT_CASE_DATA_ENTRY_BEGIN',

    EDIT_CASE_DATA_RESPONDENT: asyncActionType('[CASE_MANAGEMENT]EDIT_CASE_DATA_RESPONDENT'),
    EDIT_CASE_DATA_RESPONDENT_BEGIN: '[CASE_MANAGEMENT]EDIT_CASE_DATA_RESPONDENT_BEGIN',

    EDIT_CASE_DATA_COMPLAINANT: asyncActionType('[CASE_MANAGEMENT]EDIT_CASE_DATA_COMPLAINANT'),
    EDIT_CASE_DATA_COMPLAINANT_BEGIN: '[CASE_MANAGEMENT]EDIT_CASE_DATA_COMPLAINANT_BEGIN',

    EDIT_CASE_DATA_INCIDENT: asyncActionType('[CASE_MANAGEMENT]EDIT_CASE_DATA_INCIDENT'),
    EDIT_CASE_DATA_INCIDENT_BEGIN: '[CASE_MANAGEMENT]EDIT_CASE_DATA_INCIDENT_BEGIN',
};

export const ModalTypes = {
    CASE_ENTRY_EDIT: 'case_entry_edit',
    CASE_ENTRY_ADD: 'case_entry_add',
    CASE_FILE_UPLOAD: 'case_file_upload',
};

export const CASE_DETAIL_TABS = {
    FILES: 'files',
    ENTRIES: 'entries',
};
// Status types
export const FETCH_STATUS = {
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
};

export default {
    ...FILTER_ACTIONS,
};
export const payload = {
    order: [],
    where: `{"status":{"inq":["Assigned"]}}`,
};

export const MESSAGES = {
    NO_AUDIT_HISTORY: 'No Audit History data',
    FILE_UPLOAD_SUCCESS: 'success',
    FILE_UPLOAD_FAIL: 'fail',
};

export const CASE_TYPES = {
    ASSIGNED: 'Assigned',
    INVESTIGATION_STARTED: 'Investigation Started',
    READY_TO_REVIEW: 'Ready To Review',
    CRIMINAL_HOLD: 'Criminal Hold',
    CLOSED: 'Closed',
    REFERRAL: 'Referral',
};

export const HISTORY_TYPES = {
    ADD: 'add',
    EDIT: 'edit',
    DELETE: 'delete',
    ADD_ACTIVITY: 'addActivity',
    EDIT_ACTIVITY: 'editActivity',
    DELETE_ACTIVITY: 'deleteActivity',
    ADD_ATTACHMENT: 'addAttachment',
    DELETE_ATTACHMENT: 'deleteAttachment',
};
